name: SihastruCraft
main: org.sihastrucraft.eu.Main
version: 1.0
api-version: 1.16
commands:
    mark:


      description: mark chunks
      usage: /mark <tag>
    unmark:


      description: unmark chunks
      usage: /unmark
    owouwuowouwu:


      description: useless
      usage: none